name: Publish compute.wit

# Workflow to publish fastly:compute to GHCR

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      attestations: write

    env:
      WKG_VERSION: 0.15.0
      WASM_TOOLS_VERSION: 1.255.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # v1.22.0

      - name: Install wkg
        shell: bash
        run: cargo binstall -y "wkg@${{ env.WKG_VERSION }}"

      - name: Install wasm-tools
        shell: bash
        run: cargo binstall -y "wasm-tools@${{ env.WASM_TOOLS_VERSION }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_PAT }}

      - name: Build WIT package
        shell: bash
        run: |
          # We want to publish compute.wit, not adapter.wit or viceroy.wit, so
          # copy the WIT dir, delete those, and put compute.wit at the top level.
          cp -r wasm_abi/wit "$GITHUB_WORKSPACE/fastly-compute-wit"
          rm -r "$GITHUB_WORKSPACE/fastly-compute-wit/deps/fastly-adapter"
          rm "$GITHUB_WORKSPACE/fastly-compute-wit/viceroy.wit"
          mv "$GITHUB_WORKSPACE/fastly-compute-wit/deps/fastly/compute.wit" "$GITHUB_WORKSPACE/fastly-compute-wit"
          rmdir "$GITHUB_WORKSPACE/fastly-compute-wit/deps/fastly"

          # Use wasm-tools component wit instead of wkg wit build because the
          # former understands deps directories.
          wasm-tools component wit "$GITHUB_WORKSPACE/fastly-compute-wit" --wasm -o "$GITHUB_WORKSPACE/fastly-compute.wasm"

      - name: Publish to GitHub Container Registry
        id: publish
        uses: bytecodealliance/wkg-github-action@5b7005d1fc81c8c3380a059e58345033e3a97638 # `main`, at the time of this comment, because we need bytecodealliance/wkg-github-action#9
        with:
          oci-reference-without-tag: 'ghcr.io/fastly/viceroy/fastly-compute'
          file: 'fastly-compute.wasm'
          description: 'The APIs of the Fastly Compute platform'
          source: 'https://github.com/fastly/Viceroy'
          homepage: 'https://www.fastly.com/documentation/guides/compute/'
          version: '0.1.0'
          licenses: 'Apache-2.0 WITH LLVM-exception'

      - name: Attest build provenance
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-name: ghcr.io/fastly/viceroy/fastly-compute
          subject-digest: ${{ steps.publish.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.ORG_PAT }}
