name: Release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  prep-release:
    runs-on: ${{ case(vars.LINUX_RUNNER_SMALL != '', vars.LINUX_RUNNER_SMALL, 'ubuntu-slim') }}
    permissions:
      contents: write
    steps:
      - name: Create draft release
        run: |
          gh release create ${TAG} --draft=true --target ${{ github.sha }}
        env:
          TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}

  build:
    needs: prep-release
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
          - macos-26-intel
          - windows-2025
        arch:
          - amd64
          - arm64
        exclude:
          - runner: ubuntu-24.04
            arch: arm64

          - runner: ubuntu-24.04-arm
            arch: amd64

          - runner: macos-26
            arch: amd64

          - runner: macos-26-intel
            arch: arm64

          - runner: windows-2025
            arch: arm64
        include:
          - runner: ubuntu-24.04
            name: linux
            rust_abi: unknown-linux-gnu

          - runner: ubuntu-24.04-arm
            name: linux
            rust_abi: unknown-linux-gnu

          - runner: macos-26
            name: darwin
            rust_abi: apple-darwin

          - runner: windows-2025
            name: windows
            rust_abi: pc-windows-msvc
            extension: .exe

          - arch: arm64
            rust_arch: aarch64

          - arch: amd64
            rust_arch: x86_64

    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        run: rustup target add ${{ matrix.rust_arch }}-${{ matrix.rust_abi }}

      - name: Build
        run: |
          cargo build --profile=release-lto-stripped --workspace --locked --target=${{ matrix.rust_arch }}-${{ matrix.rust_abi }}

      - name: Package
        run: |
          cd target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release-lto-stripped
          tar czf viceroy_${TAG}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz viceroy${{ matrix.extension }}
        env:
          TAG: ${{ github.ref_name }}

      - name: Upload to release
        run: |
          gh release upload ${TAG} target/${{ matrix.rust_arch }}-${{ matrix.rust_abi }}/release-lto-stripped/viceroy_${TAG}_${{ matrix.name }}-${{ matrix.arch }}.tar.gz --clobber
        env:
          TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Publish release
        run: |
          gh release edit ${TAG} --draft=false
        env:
          TAG: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}

  publish-lib:
    needs: build
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    uses: fastly/devex-reusable-workflows/.github/workflows/publish-rust-crates-io-v1.yml@main
    with:
      crate_name: viceroy-lib
      expected_version: ${{ github.ref_name }}

  publish-bin:
    needs: publish-lib
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    uses: fastly/devex-reusable-workflows/.github/workflows/publish-rust-crates-io-v1.yml@main
    with:
      crate_name: viceroy
      expected_version: ${{ github.ref_name }}
