name: Test using various Rust versions

on:
  schedule:
    - cron: "2 13 * * 1"
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ case(vars.LINUX_RUNNER_ARM64 != '', vars.LINUX_RUNNER_ARM64, 'ubuntu-24.04-arm') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install Rust
      run: rustup default ${{ matrix.rust }}

    - run: make ci
